DIR_SRC:=src/
DIR_OBJ:=obj/

CXX ?= g++
# CC ?= gcc

SRC_EXT:=cpp
# SRC_EXT:=c

COMPILE_FLAGS = -std=c++14 -Wall -Wextra -02

search-dir-all=$(strip $(call search-dir,$1) $(foreach DIR,$(call search-dir,$1),$(call search-dir-all,$(DIR))))

DIR_SRC_ALL:=$(DIR_SRC) $(call search-dir-all,$(DIR_SRC))
OBJ:=$(SRC:.$(EXT)=.o)
I_SRC:=$(addprefix -I,$(DIR_SRC_ALL))

RCOMPILE_FLAGS = -D NDEBUG

UNAME_S:=$(shell uname -s)

# Suffixes

INSTALL = install
INSTALL_PROGRAM = $(INSTALL)

release: export CXXFLAGS := $(CXXFLAGS) $(COMPILE_FLAGS) $(RCOMPILE_FLAGS)


OBJECTS = $(SOURCES:$(SRC_PATH)/%.$(SRC_EXT)=$(BUILD_PATH)/%.o)

release: dirs

# TODO: Handle creating directories used in the builds
# TODO: Handle executable and symlinks case
